# Configurações do Banco de Dados H2 (Em memória)
spring.datasource.url=jdbc:h2:mem:horariosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Mostra o SQL no console
spring.jpa.show-sql=true

# Atualiza as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilita o console do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.persistAuthorization=true
